USE [Crime]
GO

/****** Object:  Table [Crime].[DimYear]    Script Date: 2/3/2015 11:03:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Crime].[DimYear](
	[YearID] [int] IDENTITY(1,1) NOT NULL,
	[Year] [int] NULL,
	[ChineseNewYear] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[YearID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


